### ISSUE TITLE
flutter_pusher_client not working in IOS

### ISSUE THREAD

**Issue by junaidhashmi** [kakajansh/echo#21]
Fetching external sources
-> Fetching podspec for Flutter from Flutter
-> Fetching podspec for flutter_pusher_client from .symlinks/plugins/flutter_pusher_client/ios
[!] The flutter_pusher_client pod failed to validate due to 1 error:
- ERROR | attributes: Missing required attribute homepage.
- WARN | license: Missing license type.
- WARN | description: The description is equal to the summary.
- WARN | [iOS] keys: Missing primary key for source attribute. The acceptable ones are: git, hg, http, svn.

**Comment by Chris1234567899** [comment]
I had as well a lot of trouble with the pusher client library on android.

You can try to use another pusher library. I implemented echo with this one (which is pure dart and not trying to wrap some natives pusher libraries) and it works well so far:
https://pub.dev/packages/pusher_dart

**Comment by jinseokoh** [comment]
Just opened an PR to address `Pusher not working out of box` problem.

**Comment by heywhy** [comment]
I'm sorry the iOS support came in late because I had to learn swift to be able to support iOS, since I couldn't find a contributor build the support. But I'm glad to announce that a new version of [flutter_pusher_client](https://github.com/heywhy/flutter-pusher-client) has been released. So you are advised to upgrade to the latest version and also upgrade your flutter tools.
